# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './employee.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(1024, 692)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color: rgb(40, 40, 40)")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 20, 341, 661))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setObjectName("frame")
        self.LE_ID = QtWidgets.QLineEdit(self.frame)
        self.LE_ID.setGeometry(QtCore.QRect(100, 20, 171, 27))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(12)
        self.LE_ID.setFont(font)
        self.LE_ID.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(40, 40, 40);")
        self.LE_ID.setObjectName("LE_ID")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 20, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"Berlin Sans FB\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 65, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"Berlin Sans FB\";")
        self.label_2.setObjectName("label_2")
        self.LE_name = QtWidgets.QLineEdit(self.frame)
        self.LE_name.setGeometry(QtCore.QRect(100, 65, 171, 27))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(12)
        self.LE_name.setFont(font)
        self.LE_name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.LE_name.setObjectName("LE_name")
        self.LE_position = QtWidgets.QLineEdit(self.frame)
        self.LE_position.setGeometry(QtCore.QRect(100, 155, 171, 27))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(12)
        self.LE_position.setFont(font)
        self.LE_position.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.LE_position.setObjectName("LE_position")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 155, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"Berlin Sans FB\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(20, 110, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"Berlin Sans FB\";")
        self.label_4.setObjectName("label_4")
        self.LE_lastname = QtWidgets.QLineEdit(self.frame)
        self.LE_lastname.setGeometry(QtCore.QRect(100, 110, 171, 27))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(12)
        self.LE_lastname.setFont(font)
        self.LE_lastname.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.LE_lastname.setObjectName("LE_lastname")
        self.LE_tag = QtWidgets.QLineEdit(self.frame)
        self.LE_tag.setGeometry(QtCore.QRect(100, 245, 171, 27))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(12)
        self.LE_tag.setFont(font)
        self.LE_tag.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.LE_tag.setObjectName("LE_tag")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(20, 245, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"Berlin Sans FB\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(20, 200, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"Berlin Sans FB\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(20, 290, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"Berlin Sans FB\";")
        self.label_7.setObjectName("label_7")
        self.LE_finger = QtWidgets.QLineEdit(self.frame)
        self.LE_finger.setGeometry(QtCore.QRect(100, 290, 171, 27))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(12)
        self.LE_finger.setFont(font)
        self.LE_finger.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.LE_finger.setObjectName("LE_finger")
        self.LE_pin = QtWidgets.QLineEdit(self.frame)
        self.LE_pin.setGeometry(QtCore.QRect(100, 200, 171, 27))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(12)
        self.LE_pin.setFont(font)
        self.LE_pin.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.LE_pin.setObjectName("LE_pin")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(20, 335, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"Berlin Sans FB\";")
        self.label_8.setObjectName("label_8")
        self.CB_z1 = QtWidgets.QCheckBox(self.frame)
        self.CB_z1.setGeometry(QtCore.QRect(98, 330, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        self.CB_z1.setFont(font)
        self.CB_z1.setStyleSheet("color: rgb(255, 255, 255);")
        self.CB_z1.setIconSize(QtCore.QSize(16, 16))
        self.CB_z1.setObjectName("CB_z1")
        self.CB_z2 = QtWidgets.QCheckBox(self.frame)
        self.CB_z2.setGeometry(QtCore.QRect(158, 330, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        self.CB_z2.setFont(font)
        self.CB_z2.setStyleSheet("color: rgb(255, 255, 255);")
        self.CB_z2.setObjectName("CB_z2")
        self.CB_z3 = QtWidgets.QCheckBox(self.frame)
        self.CB_z3.setGeometry(QtCore.QRect(218, 330, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        self.CB_z3.setFont(font)
        self.CB_z3.setStyleSheet("color: rgb(255, 255, 255);")
        self.CB_z3.setObjectName("CB_z3")
        self.CAL_startdate = QtWidgets.QCalendarWidget(self.frame)
        self.CAL_startdate.setGeometry(QtCore.QRect(20, 380, 301, 191))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CAL_startdate.setFont(font)
        self.CAL_startdate.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"color: rgb(180, 180, 180);\n"
"weekend-background-color: rgb(255, 255, 127);")
        self.CAL_startdate.setGridVisible(True)
        self.CAL_startdate.setObjectName("CAL_startdate")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(130, 600, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Berlin Sans FB\";")
        self.label_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_9.setObjectName("label_9")
        self.BT_clear = QtWidgets.QPushButton(self.frame)
        self.BT_clear.setGeometry(QtCore.QRect(30, 600, 75, 31))
        self.BT_clear.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/cross-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BT_clear.setIcon(icon)
        self.BT_clear.setIconSize(QtCore.QSize(30, 30))
        self.BT_clear.setFlat(True)
        self.BT_clear.setObjectName("BT_clear")
        self.frame1 = QtWidgets.QFrame(Form)
        self.frame1.setGeometry(QtCore.QRect(360, 20, 651, 361))
        self.frame1.setFrameShape(QtWidgets.QFrame.Box)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame1.setObjectName("frame1")
        self.T_employeeInfo = QtWidgets.QTableWidget(self.frame1)
        self.T_employeeInfo.setGeometry(QtCore.QRect(10, 10, 631, 341))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(9)
        self.T_employeeInfo.setFont(font)
        self.T_employeeInfo.setStyleSheet("color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(192, 255, 133);\n"
"selection-color: rgb(0, 0, 0);")
        self.T_employeeInfo.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.T_employeeInfo.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.T_employeeInfo.setColumnCount(9)
        self.T_employeeInfo.setObjectName("T_employeeInfo")
        self.T_employeeInfo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.T_employeeInfo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.T_employeeInfo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.T_employeeInfo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.T_employeeInfo.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.T_employeeInfo.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.T_employeeInfo.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.T_employeeInfo.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.T_employeeInfo.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.T_employeeInfo.setHorizontalHeaderItem(8, item)
        self.T_employeeInfo.horizontalHeader().setVisible(True)
        self.T_employeeInfo.horizontalHeader().setDefaultSectionSize(70)
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(360, 400, 651, 281))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.BT_add = QtWidgets.QPushButton(self.frame_3)
        self.BT_add.setGeometry(QtCore.QRect(50, 40, 131, 91))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.BT_add.setFont(font)
        self.BT_add.setStyleSheet("")
        self.BT_add.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BT_add.setIcon(icon1)
        self.BT_add.setIconSize(QtCore.QSize(100, 100))
        self.BT_add.setFlat(True)
        self.BT_add.setObjectName("BT_add")
        self.BT_edit = QtWidgets.QPushButton(self.frame_3)
        self.BT_edit.setGeometry(QtCore.QRect(250, 40, 161, 101))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.BT_edit.setFont(font)
        self.BT_edit.setStyleSheet("")
        self.BT_edit.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/Edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BT_edit.setIcon(icon2)
        self.BT_edit.setIconSize(QtCore.QSize(100, 100))
        self.BT_edit.setFlat(True)
        self.BT_edit.setObjectName("BT_edit")
        self.BT_delete = QtWidgets.QPushButton(self.frame_3)
        self.BT_delete.setGeometry(QtCore.QRect(460, 30, 161, 111))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.BT_delete.setFont(font)
        self.BT_delete.setStyleSheet("")
        self.BT_delete.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/Del.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BT_delete.setIcon(icon3)
        self.BT_delete.setIconSize(QtCore.QSize(100, 100))
        self.BT_delete.setFlat(True)
        self.BT_delete.setObjectName("BT_delete")
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(200, 210, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.LE_search = QtWidgets.QLineEdit(self.frame_3)
        self.LE_search.setGeometry(QtCore.QRect(240, 200, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(12)
        self.LE_search.setFont(font)
        self.LE_search.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(40, 40, 40);")
        self.LE_search.setObjectName("LE_search")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setGeometry(QtCore.QRect(130, 190, 91, 61))
        self.pushButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("img/search2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon4)
        self.pushButton.setIconSize(QtCore.QSize(60, 60))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.BT_home = QtWidgets.QPushButton(self.frame_3)
        self.BT_home.setGeometry(QtCore.QRect(570, 220, 75, 51))
        self.BT_home.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("img/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BT_home.setIcon(icon5)
        self.BT_home.setIconSize(QtCore.QSize(60, 60))
        self.BT_home.setFlat(True)
        self.BT_home.setObjectName("BT_home")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "     E M P L O Y E E"))
        self.label.setText(_translate("Form", "ID"))
        self.label_2.setText(_translate("Form", "Name"))
        self.label_3.setText(_translate("Form", "Position"))
        self.label_4.setText(_translate("Form", "Lastname"))
        self.label_5.setText(_translate("Form", "Tag"))
        self.label_6.setText(_translate("Form", "Pin"))
        self.label_7.setText(_translate("Form", "Finger"))
        self.label_8.setText(_translate("Form", "Privilege"))
        self.CB_z1.setText(_translate("Form", "Zone 1"))
        self.CB_z2.setText(_translate("Form", "Zone 2"))
        self.CB_z3.setText(_translate("Form", "Zone 3"))
        self.label_9.setText(_translate("Form", "Start Date"))
        item = self.T_employeeInfo.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.T_employeeInfo.horizontalHeaderItem(1)
        item.setText(_translate("Form", "name"))
        item = self.T_employeeInfo.horizontalHeaderItem(2)
        item.setText(_translate("Form", "lastName"))
        item = self.T_employeeInfo.horizontalHeaderItem(3)
        item.setText(_translate("Form", "position"))
        item = self.T_employeeInfo.horizontalHeaderItem(4)
        item.setText(_translate("Form", "startDate"))
        item = self.T_employeeInfo.horizontalHeaderItem(5)
        item.setText(_translate("Form", "pin"))
        item = self.T_employeeInfo.horizontalHeaderItem(6)
        item.setText(_translate("Form", "tag"))
        item = self.T_employeeInfo.horizontalHeaderItem(7)
        item.setText(_translate("Form", "finger"))
        item = self.T_employeeInfo.horizontalHeaderItem(8)
        item.setText(_translate("Form", "previlege"))


