# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './empHistory.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormEmpHist(object):
    def setupUi(self, FormEmpHist):
        FormEmpHist.setObjectName("FormEmpHist")
        FormEmpHist.resize(561, 547)
        FormEmpHist.setStyleSheet("background-color: rgb(40, 40, 40)")
        self.T_EmpHisto = QtWidgets.QTableWidget(FormEmpHist)
        self.T_EmpHisto.setGeometry(QtCore.QRect(20, 60, 521, 281))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(12)
        self.T_EmpHisto.setFont(font)
        self.T_EmpHisto.setAutoFillBackground(False)
        self.T_EmpHisto.setStyleSheet("color:white;")
        self.T_EmpHisto.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.T_EmpHisto.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.T_EmpHisto.setObjectName("T_EmpHisto")
        self.T_EmpHisto.setColumnCount(2)
        self.T_EmpHisto.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.T_EmpHisto.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.T_EmpHisto.setHorizontalHeaderItem(1, item)
        self.T_EmpHisto.horizontalHeader().setCascadingSectionResizes(False)
        self.T_EmpHisto.horizontalHeader().setStretchLastSection(True)
        self.T_EmpHisto.verticalHeader().setCascadingSectionResizes(False)
        self.T_EmpHisto.verticalHeader().setStretchLastSection(False)
        self.pushButton = QtWidgets.QPushButton(FormEmpHist)
        self.pushButton.setGeometry(QtCore.QRect(30, 380, 131, 111))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/zone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(100, 100))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(FormEmpHist)
        self.label.setGeometry(QtCore.QRect(170, 420, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color : white")
        self.label.setObjectName("label")
        self.LB_currentZone = QtWidgets.QLabel(FormEmpHist)
        self.LB_currentZone.setGeometry(QtCore.QRect(300, 418, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(16)
        font.setItalic(True)
        self.LB_currentZone.setFont(font)
        self.LB_currentZone.setStyleSheet("color:white;")
        self.LB_currentZone.setObjectName("LB_currentZone")
        self.frame = QtWidgets.QFrame(FormEmpHist)
        self.frame.setGeometry(QtCore.QRect(10, 10, 531, 31))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.RB_zone1 = QtWidgets.QRadioButton(self.frame)
        self.RB_zone1.setGeometry(QtCore.QRect(90, 10, 70, 17))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.RB_zone1.setFont(font)
        self.RB_zone1.setStyleSheet("color: white;")
        self.RB_zone1.setChecked(True)
        self.RB_zone1.setObjectName("RB_zone1")
        self.RB_zone2 = QtWidgets.QRadioButton(self.frame)
        self.RB_zone2.setGeometry(QtCore.QRect(230, 10, 70, 17))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.RB_zone2.setFont(font)
        self.RB_zone2.setStyleSheet("color: white;")
        self.RB_zone2.setChecked(False)
        self.RB_zone2.setObjectName("RB_zone2")
        self.RB_zone3 = QtWidgets.QRadioButton(self.frame)
        self.RB_zone3.setGeometry(QtCore.QRect(370, 10, 70, 17))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.RB_zone3.setFont(font)
        self.RB_zone3.setStyleSheet("color: white;\n"
"")
        self.RB_zone3.setChecked(False)
        self.RB_zone3.setObjectName("RB_zone3")

        self.retranslateUi(FormEmpHist)
        QtCore.QMetaObject.connectSlotsByName(FormEmpHist)

    def retranslateUi(self, FormEmpHist):
        _translate = QtCore.QCoreApplication.translate
        FormEmpHist.setWindowTitle(_translate("FormEmpHist", "Form"))
        item = self.T_EmpHisto.horizontalHeaderItem(0)
        item.setText(_translate("FormEmpHist", "Date in"))
        item = self.T_EmpHisto.horizontalHeaderItem(1)
        item.setText(_translate("FormEmpHist", "Date out"))
        self.label.setText(_translate("FormEmpHist", "Location : "))
        self.LB_currentZone.setText(_translate("FormEmpHist", "Zone"))
        self.RB_zone1.setText(_translate("FormEmpHist", "Zone 1"))
        self.RB_zone2.setText(_translate("FormEmpHist", "Zone 2"))
        self.RB_zone3.setText(_translate("FormEmpHist", "Zone 3"))


