# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './zoneTime.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormZoneTime(object):
    def setupUi(self, FormZoneTime):
        FormZoneTime.setObjectName("FormZoneTime")
        FormZoneTime.resize(587, 428)
        FormZoneTime.setLayoutDirection(QtCore.Qt.LeftToRight)
        FormZoneTime.setStyleSheet("background-color:rgb(40, 40, 40);")
        self.TE_zone1From = QtWidgets.QTimeEdit(FormZoneTime)
        self.TE_zone1From.setGeometry(QtCore.QRect(220, 50, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.TE_zone1From.setFont(font)
        self.TE_zone1From.setStyleSheet("color:white;\n"
"background-color:rgb(60, 60, 60);\n"
"font: 10pt \"Berlin Sans FB\";")
        self.TE_zone1From.setObjectName("TE_zone1From")
        self.label = QtWidgets.QLabel(FormZoneTime)
        self.label.setGeometry(QtCore.QRect(40, 60, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(FormZoneTime)
        self.label_2.setGeometry(QtCore.QRect(160, 60, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(200, 200, 200);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(FormZoneTime)
        self.label_3.setGeometry(QtCore.QRect(390, 60, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(200, 200, 200);")
        self.label_3.setObjectName("label_3")
        self.TE_zone1To = QtWidgets.QTimeEdit(FormZoneTime)
        self.TE_zone1To.setGeometry(QtCore.QRect(430, 50, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.TE_zone1To.setFont(font)
        self.TE_zone1To.setStyleSheet("color:white;\n"
"background-color:rgb(60, 60, 60);\n"
"font: 10pt \"Berlin Sans FB\";")
        self.TE_zone1To.setObjectName("TE_zone1To")
        self.label_4 = QtWidgets.QLabel(FormZoneTime)
        self.label_4.setGeometry(QtCore.QRect(160, 120, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(200, 200, 200);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(FormZoneTime)
        self.label_5.setGeometry(QtCore.QRect(40, 120, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:white;")
        self.label_5.setObjectName("label_5")
        self.TE_zone2To = QtWidgets.QTimeEdit(FormZoneTime)
        self.TE_zone2To.setGeometry(QtCore.QRect(430, 110, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.TE_zone2To.setFont(font)
        self.TE_zone2To.setStyleSheet("color:white;\n"
"background-color:rgb(60, 60, 60);\n"
"font: 10pt \"Berlin Sans FB\";")
        self.TE_zone2To.setObjectName("TE_zone2To")
        self.label_6 = QtWidgets.QLabel(FormZoneTime)
        self.label_6.setGeometry(QtCore.QRect(390, 120, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgb(200, 200, 200);")
        self.label_6.setObjectName("label_6")
        self.TE_zone2From = QtWidgets.QTimeEdit(FormZoneTime)
        self.TE_zone2From.setGeometry(QtCore.QRect(220, 110, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.TE_zone2From.setFont(font)
        self.TE_zone2From.setStyleSheet("color:white;\n"
"background-color:rgb(60, 60, 60);\n"
"font: 10pt \"Berlin Sans FB\";")
        self.TE_zone2From.setObjectName("TE_zone2From")
        self.label_7 = QtWidgets.QLabel(FormZoneTime)
        self.label_7.setGeometry(QtCore.QRect(160, 180, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgb(200, 200, 200);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(FormZoneTime)
        self.label_8.setGeometry(QtCore.QRect(40, 180, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:white;")
        self.label_8.setObjectName("label_8")
        self.TE_zone3To = QtWidgets.QTimeEdit(FormZoneTime)
        self.TE_zone3To.setGeometry(QtCore.QRect(430, 170, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.TE_zone3To.setFont(font)
        self.TE_zone3To.setStyleSheet("color:white;\n"
"background-color:rgb(60, 60, 60);\n"
"font: 10pt \"Berlin Sans FB\";")
        self.TE_zone3To.setObjectName("TE_zone3To")
        self.label_9 = QtWidgets.QLabel(FormZoneTime)
        self.label_9.setGeometry(QtCore.QRect(390, 180, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:rgb(200, 200, 200);")
        self.label_9.setObjectName("label_9")
        self.TE_zone3From = QtWidgets.QTimeEdit(FormZoneTime)
        self.TE_zone3From.setGeometry(QtCore.QRect(220, 170, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.TE_zone3From.setFont(font)
        self.TE_zone3From.setStyleSheet("color:white;\n"
"background-color:rgb(60, 60, 60);\n"
"font: 10pt \"Berlin Sans FB\";")
        self.TE_zone3From.setObjectName("TE_zone3From")
        self.BT_validate = QtWidgets.QPushButton(FormZoneTime)
        self.BT_validate.setGeometry(QtCore.QRect(140, 290, 101, 81))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/validate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BT_validate.setIcon(icon)
        self.BT_validate.setIconSize(QtCore.QSize(120, 120))
        self.BT_validate.setFlat(True)
        self.BT_validate.setObjectName("BT_validate")
        self.BT_cancel = QtWidgets.QPushButton(FormZoneTime)
        self.BT_cancel.setGeometry(QtCore.QRect(330, 290, 101, 81))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/cross-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BT_cancel.setIcon(icon1)
        self.BT_cancel.setIconSize(QtCore.QSize(80, 80))
        self.BT_cancel.setFlat(True)
        self.BT_cancel.setObjectName("BT_cancel")
        self.BT_home = QtWidgets.QPushButton(FormZoneTime)
        self.BT_home.setGeometry(QtCore.QRect(510, 370, 75, 51))
        self.BT_home.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BT_home.setIcon(icon2)
        self.BT_home.setIconSize(QtCore.QSize(60, 60))
        self.BT_home.setFlat(True)
        self.BT_home.setObjectName("BT_home")

        self.retranslateUi(FormZoneTime)
        QtCore.QMetaObject.connectSlotsByName(FormZoneTime)

    def retranslateUi(self, FormZoneTime):
        _translate = QtCore.QCoreApplication.translate
        FormZoneTime.setWindowTitle(_translate("FormZoneTime", "   Z O N E     T I M E"))
        self.label.setText(_translate("FormZoneTime", "Zone 1"))
        self.label_2.setText(_translate("FormZoneTime", "from"))
        self.label_3.setText(_translate("FormZoneTime", "to"))
        self.label_4.setText(_translate("FormZoneTime", "from"))
        self.label_5.setText(_translate("FormZoneTime", "Zone 2"))
        self.label_6.setText(_translate("FormZoneTime", "to"))
        self.label_7.setText(_translate("FormZoneTime", "from"))
        self.label_8.setText(_translate("FormZoneTime", "Zone 3"))
        self.label_9.setText(_translate("FormZoneTime", "to"))


